import { BISTStock, SectorType } from '@/types/stock';
import { evaluateBISTStock } from './scoring-engine';

export interface RawStockItem {
  symbol: string;
  name: string;
  sector: SectorType;
}

export const CURATED_BIST_RAW: RawStockItem[] = [
  { symbol: 'THYAO', name: 'Türk Hava Yolları', sector: 'Havacılık' },
  { symbol: 'TRALT', name: 'Trakya Altın ve Madencilik A.Ş.', sector: 'Madencilik & Değerli Metal' },
  { symbol: 'ASELS', name: 'Aselsan Elektronik Sanayi', sector: 'Savunma Sanayi' },
  { symbol: 'TUPRS', name: 'Tüpraş - Petrol Rafinerileri', sector: 'Enerji' },
  { symbol: 'GARAN', name: 'Garanti BBVA', sector: 'Bankacılık' },
  { symbol: 'BIMAS', name: 'BİM Birleşik Mağazalar', sector: 'Perakende' },
  { symbol: 'KCHOL', name: 'Koç Holding', sector: 'Holding' },
  { symbol: 'ASTOR', name: 'Astor Enerji A.Ş.', sector: 'Enerji' },
  { symbol: 'FROTO', name: 'Ford Otomotiv Sanayi', sector: 'Otomotiv' },
  { symbol: 'SISE', name: 'Şişecam Fabrikaları', sector: 'Cam & Çimento' },
  { symbol: 'AKBNK', name: 'Akbank T.A.Ş.', sector: 'Bankacılık' },
  { symbol: 'YKBNK', name: 'Yapı ve Kredi Bankası', sector: 'Bankacılık' },
  { symbol: 'ISCTR', name: 'Türkiye İş Bankası (C)', sector: 'Bankacılık' },
  { symbol: 'VAKBN', name: 'Türkiye Vakıflar Bankası', sector: 'Bankacılık' },
  { symbol: 'HALKB', name: 'Türkiye Halk Bankası', sector: 'Bankacılık' },
  { symbol: 'TSKB', name: 'T.S.K.B.', sector: 'Bankacılık' },
  { symbol: 'SAHOL', name: 'Sabancı Holding', sector: 'Holding' },
  { symbol: 'AGHOL', name: 'Anadolu Grubu Holding', sector: 'Holding' },
  { symbol: 'DOHOL', name: 'Doğan Holding', sector: 'Holding' },
  { symbol: 'BERA', name: 'Bera Holding', sector: 'Holding' },
  { symbol: 'PGSUS', name: 'Pegasus Hava Taşımacılığı', sector: 'Havacılık' },
  { symbol: 'TAVHL', name: 'TAV Havalimanları', sector: 'Havacılık' },
  { symbol: 'CLEBI', name: 'Çelebi Hava Servisi', sector: 'Havacılık' },
  { symbol: 'MGROS', name: 'Migros Ticaret', sector: 'Perakende' },
  { symbol: 'SOKM', name: 'Şok Marketler', sector: 'Perakende' },
  { symbol: 'CCOLA', name: 'Coca-Cola İçecek', sector: 'Perakende' },
  { symbol: 'AEFES', name: 'Anadolu Efes', sector: 'Perakende' },
  { symbol: 'TOASO', name: 'Tofaş Türk Otomobil Fabrikası', sector: 'Otomotiv' },
  { symbol: 'DOAS', name: 'Doğuş Otomotiv', sector: 'Otomotiv' },
  { symbol: 'OTKAR', name: 'Otokar Otomotiv ve Savunma', sector: 'Otomotiv' },
  { symbol: 'ENJSA', name: 'Enerjisa Enerji', sector: 'Enerji' },
  { symbol: 'AKSEN', name: 'Aksa Enerji', sector: 'Enerji' },
  { symbol: 'KONTR', name: 'Kontrolmatik Teknoloji & Enerji', sector: 'Enerji' },
  { symbol: 'GESAN', name: 'Girişim Elektrik Sanayi', sector: 'Enerji' },
  { symbol: 'EUPWR', name: 'Europower Enerji', sector: 'Enerji' },
  { symbol: 'CWENE', name: 'CW Enerji', sector: 'Enerji' },
  { symbol: 'YEOTK', name: 'YEO Teknoloji Enerji', sector: 'Enerji' },
  { symbol: 'SMRTG', name: 'Smart Güneş Enerjisi', sector: 'Enerji' },
  { symbol: 'ODAS', name: 'Odaş Elektrik Üretim', sector: 'Enerji' },
  { symbol: 'CANTE', name: 'Çan2 Termik A.Ş.', sector: 'Enerji' },
  { symbol: 'EREGL', name: 'Ereğli Demir ve Çelik', sector: 'Sanayi & Üretim' },
  { symbol: 'KRDMD', name: 'Kardemir (D)', sector: 'Sanayi & Üretim' },
  { symbol: 'OYAKC', name: 'Oyak Çimento', sector: 'Cam & Çimento' },
  { symbol: 'CIMSA', name: 'Çimsa Çimento', sector: 'Cam & Çimento' },
  { symbol: 'AKCNS', name: 'Akçansa Çimento', sector: 'Cam & Çimento' },
  { symbol: 'BRSAN', name: 'Borusan Boru', sector: 'Sanayi & Üretim' },
  { symbol: 'KCAER', name: 'Kocaer Çelik', sector: 'Sanayi & Üretim' },
  { symbol: 'EGEEN', name: 'Ege Endüstri', sector: 'Sanayi & Üretim' },
  { symbol: 'KONYA', name: 'Konya Çimento', sector: 'Cam & Çimento' },
  { symbol: 'BRYAT', name: 'Borusan Yatırım', sector: 'Holding' },
  { symbol: 'MIATK', name: 'Mia Teknoloji', sector: 'Teknoloji & Bilişim' },
  { symbol: 'REEDR', name: 'Reeder Teknoloji', sector: 'Teknoloji & Bilişim' },
  { symbol: 'SDTTR', name: 'SDT Uzay ve Savunma', sector: 'Savunma Sanayi' },
  { symbol: 'LOGO', name: 'Logo Yazılım', sector: 'Teknoloji & Bilişim' },
  { symbol: 'KFEIN', name: 'Kafein Yazılım', sector: 'Teknoloji & Bilişim' },
  { symbol: 'TCELL', name: 'Turkcell İletişim Hizmetleri', sector: 'Telekomünikasyon' },
  { symbol: 'TTKOM', name: 'Türk Telekom', sector: 'Telekomünikasyon' },
  { symbol: 'PETKM', name: 'Petkim Petrokimya', sector: 'Sanayi & Üretim' },
  { symbol: 'SASA', name: 'SASA Polyester Sanayi', sector: 'Sanayi & Üretim' },
  { symbol: 'HEKTS', name: 'Hektaş Ticaret', sector: 'Kimya & Gübre' },
  { symbol: 'GUBRF', name: 'Gübre Fabrikaları', sector: 'Kimya & Gübre' },
  { symbol: 'KOZAL', name: 'Koza Altın İşletmeleri', sector: 'Madencilik & Değerli Metal' },
  { symbol: 'KOZAA', name: 'Koza Anadolu Metal Madencilik', sector: 'Madencilik & Değerli Metal' },
  { symbol: 'IPEKE', name: 'İpek Doğal Enerji', sector: 'Madencilik & Değerli Metal' },
  { symbol: 'ALARK', name: 'Alarko Holding', sector: 'Holding' },
  { symbol: 'ENKAI', name: 'Enka İnşaat ve Sanayi', sector: 'Sanayi & Üretim' },
  { symbol: 'TABGD', name: 'TAB Gıda Sanayi', sector: 'Perakende' },
  { symbol: 'TARKM', name: 'Tarkim Bitki Koruma', sector: 'Kimya & Gübre' },
  { symbol: 'EBEBK', name: 'Ebebek Mağazacılık', sector: 'Perakende' },
  { symbol: 'SURGY', name: 'Sur Tatil Evleri GYO', sector: 'Gayrimenkul & GYO' },
  { symbol: 'EKGYO', name: 'Emlak Konut GYO', sector: 'Gayrimenkul & GYO' },
  { symbol: 'ISGYO', name: 'İş Gayrimenkul Yatırım Ortaklığı', sector: 'Gayrimenkul & GYO' },
  { symbol: 'TRGYO', name: 'Torunlar GYO', sector: 'Gayrimenkul & GYO' },
  { symbol: 'KZBGY', name: 'Kızılbük GYO', sector: 'Gayrimenkul & GYO' },
  { symbol: 'ANSGR', name: 'Anadolu Sigorta', sector: 'Finans & Sigorta' },
  { symbol: 'TURSG', name: 'Türkiye Sigorta', sector: 'Finans & Sigorta' },
  { symbol: 'AKGRT', name: 'Aksigorta', sector: 'Finans & Sigorta' },
  { symbol: 'ISMEN', name: 'İş Yatırım Menkul Değerler', sector: 'Finans & Sigorta' },
  { symbol: 'INFO', name: 'İnfo Yatırım Menkul Değerler', sector: 'Finans & Sigorta' },
  { symbol: 'OYAYO', name: 'Oyak Yatırım Ortaklığı', sector: 'Finans & Sigorta' },
  { symbol: 'ECILC', name: 'Eczacıbaşı İlaç', sector: 'Sağlık & İlaç' },
  { symbol: 'GENIL', name: 'Gen İlaç ve Sağlık Ürünleri', sector: 'Sağlık & İlaç' },
  { symbol: 'SELEC', name: 'Selçuk Ecza Deposu', sector: 'Sağlık & İlaç' },
  { symbol: 'AGROT', name: 'Agrotech Yüksek Teknoloji', sector: 'Teknoloji & Bilişim' },
  { symbol: 'BINHO', name: '1000 Yatırımlar Holding', sector: 'Teknoloji & Bilişim' },
  { symbol: 'ARCLK', name: 'Arçelik A.Ş.', sector: 'Sanayi & Üretim' },
  { symbol: 'VESTL', name: 'Vestel Elektronik', sector: 'Sanayi & Üretim' },
  { symbol: 'TMSN', name: 'Tümosan Motor ve Traktör', sector: 'Otomotiv' },
  { symbol: 'SKBNK', name: 'Şekerbank T.A.Ş.', sector: 'Bankacılık' },
  { symbol: 'ALBRK', name: 'Albaraka Türk Katılım Bankası', sector: 'Bankacılık' },
  { symbol: 'BUCIM', name: 'Bursa Çimento', sector: 'Cam & Çimento' },
  { symbol: 'BSOKE', name: 'Batısöke Söke Çimento', sector: 'Cam & Çimento' },
  { symbol: 'QUAGR', name: 'Qua Granite Hayal Yapı', sector: 'Cam & Çimento' },
  { symbol: 'MEGMT', name: 'Mega Metal Sanayi', sector: 'Sanayi & Üretim' },
  { symbol: 'KORDS', name: 'Kordsa Teknik Tekstil', sector: 'Sanayi & Üretim' },
  { symbol: 'BOSSA', name: 'Bossa Ticaret ve Sanayi', sector: 'Sanayi & Üretim' },
  { symbol: 'ZOREN', name: 'Zorlu Enerji', sector: 'Enerji' },
  { symbol: 'ENERY', name: 'Enerya Enerji', sector: 'Enerji' },
  { symbol: 'ALFAS', name: 'Alfa Solar Enerji', sector: 'Enerji' },
  { symbol: 'BFREN', name: 'Bosch Fren Sistemleri', sector: 'Sanayi & Üretim' },
  { symbol: 'ULKER', name: 'Ülker Bisküvi', sector: 'Perakende' },
  { symbol: 'TATGD', name: 'Tat Gıda Sanayi', sector: 'Perakende' },
  { symbol: 'KERVT', name: 'Kerevitaş Gıda', sector: 'Perakende' },
  { symbol: 'AKENR', name: 'Akenerji Elektrik Üretim', sector: 'Enerji' },
  { symbol: 'NTHOL', name: 'Net Holding', sector: 'Holding' },
  { symbol: 'BRISA', name: 'Brisa Bridgestone Sabancı', sector: 'Otomotiv' },
  { symbol: 'GOODY', name: 'Goodyear Lastikleri', sector: 'Otomotiv' },
  { symbol: 'PRKAB', name: 'Türk Prysmian Kablo', sector: 'Sanayi & Üretim' },
  { symbol: 'SNGYO', name: 'Sinpaş GYO', sector: 'Gayrimenkul & GYO' },
  { symbol: 'TLMAN', name: 'Trabzon Liman İşletmeciliği', sector: 'Havacılık' },
  { symbol: 'KLGYO', name: 'Kiler GYO', sector: 'Gayrimenkul & GYO' },
  { symbol: 'VKGYO', name: 'Vakıf GYO', sector: 'Gayrimenkul & GYO' },
  { symbol: 'ALKIM', name: 'Alkim Alkali Kimya', sector: 'Kimya & Gübre' },
  { symbol: 'CEMAS', name: 'Çemaş Döküm Sanayi', sector: 'Sanayi & Üretim' },
  { symbol: 'CEMTS', name: 'Çemtaş Çelik Makina', sector: 'Sanayi & Üretim' },
  { symbol: 'CUSAN', name: 'Çuhadaroğlu Metal Sanayi', sector: 'Sanayi & Üretim' },
  { symbol: 'GOLTS', name: 'Göltaş Çimento', sector: 'Cam & Çimento' },
  { symbol: 'GOZDE', name: 'Gözde Girişim', sector: 'Finans & Sigorta' },
  { symbol: 'INDES', name: 'İndeks Bilgisayar', sector: 'Teknoloji & Bilişim' },
  { symbol: 'IZENR', name: 'İzdemir Enerji', sector: 'Enerji' },
  { symbol: 'KAYSE', name: 'Kayseri Şeker Fabrikası', sector: 'Perakende' },
  { symbol: 'KRDMA', name: 'Kardemir (A)', sector: 'Sanayi & Üretim' },
  { symbol: 'KRDMB', name: 'Kardemir (B)', sector: 'Sanayi & Üretim' },
  { symbol: 'MAVI', name: 'Mavi Giyim', sector: 'Perakende' },
  { symbol: 'NETAS', name: 'Netaş Telekomünikasyon', sector: 'Telekomünikasyon' },
  { symbol: 'NUGYO', name: 'Nurol GYO', sector: 'Gayrimenkul & GYO' },
  { symbol: 'ORGE', name: 'Orge Elektrik Taahhüt', sector: 'Enerji' },
  { symbol: 'PARSN', name: 'Parsan Makina', sector: 'Sanayi & Üretim' },
  { symbol: 'RYSAS', name: 'Reysaş Lojistik', sector: 'Sanayi & Üretim' },
  { symbol: 'SMART', name: 'Smartiks Yazılım', sector: 'Teknoloji & Bilişim' },
  { symbol: 'TKNSA', name: 'Teknosa', sector: 'Teknoloji & Bilişim' },
  { symbol: 'GWIND', name: 'Galata Wind Enerji', sector: 'Enerji' },
  { symbol: 'AHGAZ', name: 'Ahlatcı Doğalgaz', sector: 'Enerji' },
  { symbol: 'AKFYE', name: 'Akfen Yenilenebilir Enerji', sector: 'Enerji' },
  { symbol: 'SAYAS', name: 'Say Yenilenebilir Enerji', sector: 'Enerji' },
  { symbol: 'BIOEN', name: 'Biotrend Çevre ve Enerji', sector: 'Enerji' },
  { symbol: 'PENTA', name: 'Penta Teknoloji Dağıtım', sector: 'Teknoloji & Bilişim' },
  { symbol: 'VBTYZ', name: 'VBT Yazılım', sector: 'Teknoloji & Bilişim' },
  { symbol: 'FORMT', name: 'Formet Metal ve Cam', sector: 'Sanayi & Üretim' },
  { symbol: 'KAREL', name: 'Karel Elektronik', sector: 'Telekomünikasyon' },
  { symbol: 'FONET', name: 'Fonet Bilgi Teknolojileri', sector: 'Teknoloji & Bilişim' },
  { symbol: 'ARDYZ', name: 'ARD Bilişim', sector: 'Teknoloji & Bilişim' },
  { symbol: 'MOBTL', name: 'Mobiltel İletişim', sector: 'Telekomünikasyon' },
  { symbol: 'EDATA', name: 'E-Data Teknoloji', sector: 'Teknoloji & Bilişim' },
  { symbol: 'BATIC', name: 'Batı Çimento', sector: 'Cam & Çimento' },
  { symbol: 'BOBET', name: 'Boğaziçi Beton', sector: 'Cam & Çimento' },
  { symbol: 'NUHCM', name: 'Nuh Çimento', sector: 'Cam & Çimento' },
  { symbol: 'KARTN', name: 'Kartonsan', sector: 'Sanayi & Üretim' },
  { symbol: 'ERBOS', name: 'Erbosan Boru', sector: 'Sanayi & Üretim' },
  { symbol: 'JANTS', name: 'Jantsa Jant Sanayi', sector: 'Otomotiv' },
  { symbol: 'EGGUB', name: 'Ege Gübre', sector: 'Kimya & Gübre' },
  { symbol: 'EGPRO', name: 'Ege Profil', sector: 'Sanayi & Üretim' },
  { symbol: 'SARKY', name: 'Sarkuysan Bakır', sector: 'Sanayi & Üretim' },
  { symbol: 'KLKIM', name: 'Kalekim Kimyevi Maddeler', sector: 'Kimya & Gübre' },
  { symbol: 'KMPUR', name: 'Kimteks Poliüretan', sector: 'Kimya & Gübre' },
  { symbol: 'TEZOL', name: 'Europap Tezol Kağıt', sector: 'Sanayi & Üretim' },
  { symbol: 'SUNTK', name: 'Sun Tekstil', sector: 'Sanayi & Üretim' },
  { symbol: 'ASGYO', name: 'Asce GYO', sector: 'Gayrimenkul & GYO' },
  { symbol: 'BEGYO', name: 'Batı Ege GYO', sector: 'Gayrimenkul & GYO' },
  { symbol: 'MHRGY', name: 'MHR GYO', sector: 'Gayrimenkul & GYO' },
  { symbol: 'AVPGY', name: 'Avrupakent GYO', sector: 'Gayrimenkul & GYO' },
  { symbol: 'OZKGY', name: 'Özak GYO', sector: 'Gayrimenkul & GYO' },
  { symbol: 'HLGYO', name: 'Halk GYO', sector: 'Gayrimenkul & GYO' },
  { symbol: 'RGYAS', name: 'Rönesans Gayrimenkul', sector: 'Gayrimenkul & GYO' },
  { symbol: 'DMRGD', name: 'DMR Unlu Mamuller', sector: 'Perakende' },
  { symbol: 'KOTON', name: 'Koton Mağazacılık', sector: 'Perakende' },
  { symbol: 'LILAK', name: 'Lila Kağıt', sector: 'Sanayi & Üretim' },
  { symbol: 'BIZIM', name: 'Bizim Toptan', sector: 'Perakende' },
  { symbol: 'TUKAS', name: 'Tukaş Gıda', sector: 'Perakende' },
  { symbol: 'ULUUN', name: 'Ulusoy Un', sector: 'Perakende' },
  { symbol: 'YYLGD', name: 'Yayla Agro Gıda', sector: 'Perakende' },
  { symbol: 'KNFRT', name: 'Konfrut Gıda', sector: 'Perakende' },
  { symbol: 'GOKNR', name: 'Göknur Gıda', sector: 'Perakende' },
  { symbol: 'KTSKR', name: 'Kütahya Şeker', sector: 'Perakende' },
  { symbol: 'SUWEN', name: 'Suwen Tekstil', sector: 'Perakende' },
  { symbol: 'DERHL', name: 'Derlüks Holding', sector: 'Holding' },
  { symbol: 'VAKKO', name: 'Vakko Tekstil', sector: 'Perakende' },
  { symbol: 'YATAS', name: 'Yataş Yatak ve Mobilya', sector: 'Sanayi & Üretim' },
  { symbol: 'DEVA', name: 'Deva Holding', sector: 'Sağlık & İlaç' },
  { symbol: 'MPARK', name: 'MLP Sağlık Hizmetleri (Medical Park)', sector: 'Sağlık & İlaç' },
  { symbol: 'LKMNH', name: 'Lokman Hekim Sağlık', sector: 'Sağlık & İlaç' },
  { symbol: 'RTALB', name: 'RTA Laboratuvarları', sector: 'Sağlık & İlaç' },
  { symbol: 'ECZYT', name: 'Eczacıbaşı Yatırım', sector: 'Holding' },
  { symbol: 'POLHO', name: 'Polisan Holding', sector: 'Holding' },
  { symbol: 'A1CAP', name: 'A1 Capital Menkul Değerler', sector: 'Finans & Sigorta' },
  { symbol: 'OZGHO', name: 'Özderici Girişim', sector: 'Finans & Sigorta' },
  { symbol: 'INVES', name: 'Investco Holding', sector: 'Holding' },
  { symbol: 'GLYHO', name: 'Global Yatırım Holding', sector: 'Holding' },
  { symbol: 'ISFIN', name: 'İş Finansal Kiralama', sector: 'Finans & Sigorta' },
  { symbol: 'ANHYT', name: 'Anadolu Hayat Emeklilik', sector: 'Finans & Sigorta' },
  { symbol: 'HRKET', name: 'Hareket Proje Taşımacılığı', sector: 'Sanayi & Üretim' },
  { symbol: 'BORLS', name: 'Borlease Otomotiv', sector: 'Otomotiv' },
  { symbol: 'PASEU', name: 'Pasifik Eurasia Lojistik', sector: 'Sanayi & Üretim' },
  { symbol: 'GSDHO', name: 'GSD Holding', sector: 'Holding' },
  { symbol: 'LMKDC', name: 'Limak Doğu Anadolu Çimento', sector: 'Cam & Çimento' },
];

export function getAllBISTStocks(liveData?: Record<string, any>): BISTStock[] {
  return CURATED_BIST_RAW.map(item => {
    // If liveData is missing or no data for symbol, return a minimal stub
    const d = liveData?.[item.symbol] || {};
    
    // We expect d to have properties calculated by useMarketData or api/stocks/route
    const price = d.price || 0;
    
    const technical = {
      rsi: d.realTechnicals?.rsi14 || 50,
      macd: d.realTechnicals?.macd || { macd: 0, signal: 0, histogram: 0, bullishCross: false },
      movingAverages: {
        sma20: d.realTechnicals?.sma20 || price,
        sma50: d.realTechnicals?.sma50 || price,
        sma200: d.realTechnicals?.sma200 || price,
        priceAboveSma20: price > (d.realTechnicals?.sma20 || price),
        priceAboveSma50: price > (d.realTechnicals?.sma50 || price),
        priceAboveSma200: price > (d.realTechnicals?.sma200 || price),
        goldenCross: (d.realTechnicals?.sma50 || 0) > (d.realTechnicals?.sma200 || 0)
      },
      bollinger: d.realTechnicals?.bollinger || { upper: price, middle: price, lower: price, bandwidth: 0, squeeze: false },
      foreignOwnership: {
        currentRatio: 0, weeklyChange: 0, monthlyChange: 0, netFlowTrend: 'NÖTR', topCustodyBrokers: []
      },
      priceAction: {
        trend: price > (d.realTechnicals?.sma50 || price) ? 'YÜKSELİŞ' : 'DÜŞÜŞ',
        pattern: 'Teyit Bekleniyor',
        supportLevel: d.realTechnicals?.sma50 || price,
        resistanceLevel: d.realTechnicals?.sma20 || price,
        stopLossLevel: d.realTechnicals?.sma50 || price,
        riskRewardRatio: 0,
        nearKeySupport: false,
        breakoutConfirmed: false,
        notes: ''
      }
    };

    const fundamental = {
      pe: d.pe || 0,
      pb: d.pb || 0,
      evEbitda: d.evEbitda || 0,
      roe: d.roe || 0,
      netDebtEbitda: 0,
      netProfitMargin: 0,
      revenueGrowthYoY: 0,
      dividendYield: 0,
      sectorPeAvg: 0,
      valuationDiscount: 0
    };

    const analysts = {
      consensusTarget: price * 1.15, // fallback
      currentPrice: price,
      upsidePotential: 15,
      recommendations: { strongBuy: 0, buy: 0, hold: 0, sell: 0 },
      reports: []
    };

    const sentiment = {
      kapSentimentScore: 50,
      kapPositiveCount: 0,
      kapNegativeCount: 0,
      recentKAPNews: [],
      socialVolume: 0,
      socialSentimentScore: 50,
      socialTrend: 'NORMAL',
      communityPerception: ''
    };
    
    // We disable full scoring temporarily or pass minimal to evaluateBISTStock
    // Actually evaluateBISTStock expects all these. We will refactor it.
    
    // As a placeholder, return minimal object matching BISTStock
    const score = evaluateBISTStock(item.symbol, price, technical as any, fundamental as any, analysts as any, sentiment as any, undefined, d.high52w||price, d.low52w||price);

    return {
      symbol: item.symbol,
      name: item.name,
      sector: item.sector,
      currentPrice: price,
      changePercent: d.change || 0,
      high52w: d.high52w || price,
      low52w: d.low52w || price,
      volume24h: d.volume || 0,
      marketCap: d.marketCap || 0,
      technical: technical as any,
      fundamental: fundamental as any,
      analysts: analysts as any,
      sentiment: sentiment as any,
      score
    };
  });
}
